apiVersion: v1
kind: Namespace
metadata:
  name: svc-svc-test
---        
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: test-cluster-local-svc
  namespace: svc-svc-test
  labels:
    serving.knative.dev/visibility: "cluster-local" 
spec:
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        sidecar.istio.io/inject: "false"        
    spec:
      containers:
      - image: github.com/itsmurugappan/ksvc-ksvc/cmd/clusterlocalsvc
        ports:
        - containerPort: 8080
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: test-ingress-svc
  namespace: svc-svc-test
spec:
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - image: github.com/itsmurugappan/ksvc-ksvc/cmd/ingresssvc
        env:
        - name: svc-url
          value: "http://test-cluster-local-svc.svc-svc-test.svc.cluster.local"      
        ports:
        - containerPort: 8080
---        