apiVersion: v1
kind: Namespace
metadata:
  name: knative-examples
  labels:
    istio-injection: "enabled"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cluster-local-svc
  namespace: knative-examples
  labels:
    serving.knative.dev/visibility: "cluster-local"
spec:
  template:
    spec:
      containers:
      - image: ko://github.com/itsmurugappan/knative-examples/cmd/clusterlocalsvc
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ingress-svc
  namespace: knative-examples
spec:
  template:
    spec:
      containers:
      - image: ko://github.com/itsmurugappan/knative-examples/cmd/ingresssvc
        env:
        - name: svc-url
          value: "http://cluster-local-svc.knative-examples.svc.cluster.local"
---